import type { MenuCatalog, MenuCatalogRepository } from "../domain/menu";

const MENU_CATALOG = {
  menuItems: [
    {
      id: "kake-soba-hot",
      name: "かけそば",
      category: "麺",
      noodleKind: "そば",
      hotCold: "温",
      calories: 330,
      largeServingCalories: 141,
    },
    {
      id: "kake-udon-hot",
      name: "かけうどん",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 282,
      largeServingCalories: 87,
    },
    {
      id: "mori-soba-cold",
      name: "もりそば",
      category: "麺",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 300,
      largeServingCalories: 140,
    },
    {
      id: "mori-udon-cold",
      name: "もりうどん",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 273,
      largeServingCalories: 95,
    },
    {
      id: "zaru-soba-cold",
      name: "ざるそば",
      category: "麺",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 309,
      largeServingCalories: 140,
    },
    {
      id: "zaru-udon-cold",
      name: "ざるうどん",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 282,
      largeServingCalories: 95,
    },
    {
      id: "nimai-mori-soba-cold",
      name: "二枚もりそば",
      category: "麺",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 630,
      largeServingCalories: null,
    },
    {
      id: "nimai-mori-udon-cold",
      name: "二枚もりうどん",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 574,
      largeServingCalories: null,
    },
    {
      id: "kakiage-soba-hot",
      name: "かき揚げそば",
      category: "麺",
      noodleKind: "そば",
      hotCold: "温",
      calories: 570,
      largeServingCalories: 141,
    },
    {
      id: "kakiage-udon-hot",
      name: "かき揚げうどん",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 522,
      largeServingCalories: 87,
    },
    {
      id: "kakiage-seiro-cold",
      name: "かき揚げせいろ",
      category: "麺",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 550,
      largeServingCalories: 140,
    },
    {
      id: "kakiage-udon-seiro-cold",
      name: "かき揚げうどんせいろ",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 523,
      largeServingCalories: 95,
    },
    {
      id: "kakiage-tamago-soba-hot",
      name: "かき揚げ玉子そば",
      category: "麺",
      noodleKind: "そば",
      hotCold: "温",
      calories: 661,
      largeServingCalories: 141,
    },
    {
      id: "kakiage-tamago-udon-hot",
      name: "かき揚げ玉子うどん",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 613,
      largeServingCalories: 87,
    },
    {
      id: "kakiage-tamago-seiro-cold",
      name: "かき揚げ玉子せいろ",
      category: "麺",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 641,
      largeServingCalories: 140,
    },
    {
      id: "kakiage-tamago-udon-seiro-cold",
      name: "かき揚げ玉子うどんせいろ",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 614,
      largeServingCalories: 95,
    },
    {
      id: "ika-soba-hot",
      name: "いか天そば",
      category: "麺",
      noodleKind: "そば",
      hotCold: "温",
      calories: 396,
      largeServingCalories: 141,
    },
    {
      id: "ika-udon-hot",
      name: "いか天うどん",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 348,
      largeServingCalories: 87,
    },
    {
      id: "ika-seiro-cold",
      name: "いか天せいろ",
      category: "麺",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 376,
      largeServingCalories: 140,
    },
    {
      id: "ika-udon-seiro-cold",
      name: "いか天せいろ(うどん)",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 349,
      largeServingCalories: 95,
    },
    {
      id: "ebi-soba-hot",
      name: "えび天そば",
      category: "麺",
      noodleKind: "そば",
      hotCold: "温",
      calories: 460,
      largeServingCalories: 141,
    },
    {
      id: "ebi-udon-hot",
      name: "えび天うどん",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 412,
      largeServingCalories: 87,
    },
    {
      id: "ebi-seiro-cold",
      name: "えび天せいろ",
      category: "麺",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 440,
      largeServingCalories: 140,
    },
    {
      id: "ebi-udon-seiro-cold",
      name: "えび天せいろ(うどん)",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 413,
      largeServingCalories: 95,
    },
    {
      id: "torikara-soba-hot",
      name: "鳥からそば",
      category: "麺",
      noodleKind: "そば",
      hotCold: "温",
      calories: 580,
      largeServingCalories: 141,
    },
    {
      id: "torikara-udon-hot",
      name: "鳥からうどん",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 532,
      largeServingCalories: 87,
    },
    {
      id: "torikara-seiro-cold",
      name: "鳥からせいろ",
      category: "麺",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 560,
      largeServingCalories: 140,
    },
    {
      id: "torikara-udon-seiro-cold",
      name: "鳥からうどんせいろ",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 533,
      largeServingCalories: 95,
    },
    {
      id: "tanuki-soba-hot",
      name: "たぬきそば",
      category: "麺",
      noodleKind: "そば",
      hotCold: "温",
      calories: 475,
      largeServingCalories: 141,
    },
    {
      id: "tanuki-udon-hot",
      name: "たぬきうどん",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 421,
      largeServingCalories: 87,
    },
    {
      id: "hiyashi-tanuki-soba-cold",
      name: "冷したぬき",
      category: "麺",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 470,
      largeServingCalories: 140,
    },
    {
      id: "hiyashi-tanuki-udon-cold",
      name: "冷したぬき(うどん)",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 443,
      largeServingCalories: 95,
    },
    {
      id: "nimai-hiyashi-tanuki-soba-cold",
      name: "二枚冷したぬきそば",
      category: "麺",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 760,
      largeServingCalories: null,
    },
    {
      id: "nimai-hiyashi-tanuki-udon-cold",
      name: "二枚冷したぬきうどん",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 706,
      largeServingCalories: null,
    },
    {
      id: "kitsune-soba-hot",
      name: "きつねそば",
      category: "麺",
      noodleKind: "そば",
      hotCold: "温",
      calories: 453,
      largeServingCalories: 141,
    },
    {
      id: "kitsune-udon-hot",
      name: "きつねうどん",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 405,
      largeServingCalories: 87,
    },
    {
      id: "hiyashi-kitsune-soba-cold",
      name: "冷しきつねそば",
      category: "麺",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 448,
      largeServingCalories: 140,
    },
    {
      id: "hiyashi-kitsune-udon-cold",
      name: "冷しきつねうどん",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 421,
      largeServingCalories: 95,
    },
    {
      id: "nimai-hiyashi-kitsune-soba-cold",
      name: "二枚冷しきつねそば",
      category: "麺",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 730,
      largeServingCalories: null,
    },
    {
      id: "nimai-hiyashi-kitsune-udon-cold",
      name: "二枚冷しきつねうどん",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 684,
      largeServingCalories: null,
    },
    {
      id: "tsukimi-soba-hot",
      name: "月見そば",
      category: "麺",
      noodleKind: "そば",
      hotCold: "温",
      calories: 492,
      largeServingCalories: 141,
    },
    {
      id: "tsukimi-udon-hot",
      name: "月見うどん",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 444,
      largeServingCalories: 87,
    },
    {
      id: "yamakake-soba-hot",
      name: "山かけそば",
      category: "麺",
      noodleKind: "そば",
      hotCold: "温",
      calories: 388,
      largeServingCalories: 141,
    },
    {
      id: "yamakake-udon-hot",
      name: "山かけうどん",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 340,
      largeServingCalories: 87,
    },
    {
      id: "yamakake-seiro-cold",
      name: "山かけせいろ",
      category: "麺",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 369,
      largeServingCalories: 140,
    },
    {
      id: "yamakake-udon-seiro-cold",
      name: "山かけうどんせいろ",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 324,
      largeServingCalories: 95,
    },
    {
      id: "oroshi-seiro-cold",
      name: "おろしせいろ",
      category: "麺",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 349,
      largeServingCalories: 140,
    },
    {
      id: "oroshi-udon-seiro-cold",
      name: "おろしせいろうどん",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 322,
      largeServingCalories: 95,
    },
    {
      id: "tsukiyo-no-bakashi-soba-hot",
      name: "月夜のばかしそば",
      category: "麺",
      noodleKind: "そば",
      hotCold: "温",
      calories: 611,
      largeServingCalories: 141,
    },
    {
      id: "tsukiyo-no-bakashi-udon-hot",
      name: "月夜のばかしうどん",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 561,
      largeServingCalories: 87,
    },
    {
      id: "tsukiyo-no-bakashi-soba-cold",
      name: "冷し月夜のばかしそば",
      category: "麺",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 612,
      largeServingCalories: 140,
    },
    {
      id: "tsukiyo-no-bakashi-udon-cold",
      name: "冷し月夜のばかしうどん",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 584,
      largeServingCalories: 95,
    },
    {
      id: "kamo-seiro-cold",
      name: "鴨せいろ",
      category: "麺",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 712,
      largeServingCalories: 140,
    },
    {
      id: "kamo-udon-seiro-cold",
      name: "鴨せいろうどん",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 684,
      largeServingCalories: 95,
    },
    {
      id: "kamo-nanban-soba-hot",
      name: "鴨南蛮",
      category: "麺",
      noodleKind: "そば",
      hotCold: "温",
      calories: 711,
      largeServingCalories: 141,
    },
    {
      id: "kamo-nanban-udon-hot",
      name: "鴨南蛮うどん",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 661,
      largeServingCalories: 87,
    },
    {
      id: "joten-don",
      name: "上天丼",
      category: "丼単品",
      noodleKind: "なし",
      hotCold: null,
      calories: 698,
      largeServingCalories: null,
    },
    {
      id: "tendon",
      name: "天丼",
      category: "丼単品",
      noodleKind: "なし",
      hotCold: null,
      calories: 808,
      largeServingCalories: null,
    },
    {
      id: "curry-don",
      name: "カレー丼",
      category: "丼単品",
      noodleKind: "なし",
      hotCold: null,
      calories: 616,
      largeServingCalories: null,
    },
    {
      id: "oyakodon",
      name: "親子丼",
      category: "丼単品",
      noodleKind: "なし",
      hotCold: null,
      calories: 657,
      largeServingCalories: null,
    },
    {
      id: "hirekatsu-don",
      name: "ヒレカツ丼",
      category: "丼単品",
      noodleKind: "なし",
      hotCold: null,
      calories: 792,
      largeServingCalories: null,
    },
    {
      id: "manpuku-joten-soba",
      name: "上天丼セット",
      category: "満腹セット",
      noodleKind: "そば",
      hotCold: "温",
      calories: 1028,
      largeServingCalories: null,
    },
    {
      id: "manpuku-joten-udon",
      name: "上天丼セット(うどん)",
      category: "満腹セット",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 980,
      largeServingCalories: null,
    },
    {
      id: "manpuku-joten-seiro-cold",
      name: "上天丼セット(せいろ)",
      category: "満腹セット",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 998,
      largeServingCalories: null,
    },
    {
      id: "manpuku-joten-udon-seiro-cold",
      name: "上天丼セット(うどんせいろ)",
      category: "満腹セット",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 971,
      largeServingCalories: null,
    },
    {
      id: "manpuku-ten-soba-hot",
      name: "天丼セット",
      category: "満腹セット",
      noodleKind: "そば",
      hotCold: "温",
      calories: 1138,
      largeServingCalories: null,
    },
    {
      id: "manpuku-ten-udon-hot",
      name: "天丼セット(うどん)",
      category: "満腹セット",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 1090,
      largeServingCalories: null,
    },
    {
      id: "manpuku-ten-seiro-cold",
      name: "天丼セット(せいろ)",
      category: "満腹セット",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 1108,
      largeServingCalories: null,
    },
    {
      id: "manpuku-ten-udon-seiro-cold",
      name: "天丼セット(うどんせいろ)",
      category: "満腹セット",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 1081,
      largeServingCalories: null,
    },
    {
      id: "manpuku-curry-soba-hot",
      name: "カレー丼セット(大)",
      category: "満腹セット",
      noodleKind: "そば",
      hotCold: "温",
      calories: 946,
      largeServingCalories: null,
    },
    {
      id: "manpuku-curry-udon-hot",
      name: "カレー丼セット(大・うどん)",
      category: "満腹セット",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 898,
      largeServingCalories: null,
    },
    {
      id: "manpuku-curry-seiro-cold",
      name: "カレー丼セット(大・せいろ)",
      category: "満腹セット",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 916,
      largeServingCalories: null,
    },
    {
      id: "manpuku-curry-udon-seiro-cold",
      name: "カレー丼セット(大・うどんせいろ)",
      category: "満腹セット",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 889,
      largeServingCalories: null,
    },
    {
      id: "manpuku-oyako-soba",
      name: "親子丼セット(大)",
      category: "満腹セット",
      noodleKind: "そば",
      hotCold: "温",
      calories: 987,
      largeServingCalories: null,
    },
    {
      id: "manpuku-oyako-udon",
      name: "親子丼セット(大・うどん)",
      category: "満腹セット",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 939,
      largeServingCalories: null,
    },
    {
      id: "manpuku-oyako-seiro-cold",
      name: "親子丼セット(大・せいろ)",
      category: "満腹セット",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 957,
      largeServingCalories: null,
    },
    {
      id: "manpuku-oyako-udon-seiro-cold",
      name: "親子丼セット(大・うどんせいろ)",
      category: "満腹セット",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 930,
      largeServingCalories: null,
    },
    {
      id: "manpuku-hirekatsu-soba-hot",
      name: "ヒレカツ丼セット(大)",
      category: "満腹セット",
      noodleKind: "そば",
      hotCold: "温",
      calories: 1122,
      largeServingCalories: null,
    },
    {
      id: "manpuku-hirekatsu-udon-hot",
      name: "ヒレカツ丼セット(大・うどん)",
      category: "満腹セット",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 1074,
      largeServingCalories: null,
    },
    {
      id: "manpuku-hirekatsu-seiro-cold",
      name: "ヒレカツ丼セット(大・せいろ)",
      category: "満腹セット",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 1092,
      largeServingCalories: null,
    },
    {
      id: "manpuku-hirekatsu-udon-seiro-cold",
      name: "ヒレカツ丼セット(大・うどんせいろ)",
      category: "満腹セット",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 1065,
      largeServingCalories: null,
    },
    {
      id: "mini-kakiage-soba",
      name: "かき揚げ丼セット",
      category: "ミニ丼セット",
      noodleKind: "そば",
      hotCold: "温",
      calories: 871,
      largeServingCalories: 141,
    },
    {
      id: "mini-kakiage-udon",
      name: "かき揚げ丼セット(うどん)",
      category: "ミニ丼セット",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 823,
      largeServingCalories: 87,
    },
    {
      id: "mini-kakiage-seiro",
      name: "かき揚げ丼セット(せいろ)",
      category: "ミニ丼セット",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 841,
      largeServingCalories: 140,
    },
    {
      id: "mini-kakiage-udon-seiro",
      name: "かき揚げ丼セット(うどんせいろ)",
      category: "ミニ丼セット",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 814,
      largeServingCalories: 95,
    },
    {
      id: "mini-yamakake-soba",
      name: "山かけ丼セット",
      category: "ミニ丼セット",
      noodleKind: "そば",
      hotCold: "温",
      calories: 667,
      largeServingCalories: 141,
    },
    {
      id: "mini-yamakake-udon",
      name: "山かけ丼セット(うどん)",
      category: "ミニ丼セット",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 619,
      largeServingCalories: 87,
    },
    {
      id: "mini-yamakake-seiro",
      name: "山かけ丼セット(せいろ)",
      category: "ミニ丼セット",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 637,
      largeServingCalories: 140,
    },
    {
      id: "mini-yamakake-udon-seiro",
      name: "山かけ丼セット(うどんせいろ)",
      category: "ミニ丼セット",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 610,
      largeServingCalories: 95,
    },
    {
      id: "mini-torikara-soba",
      name: "鳥から丼セット",
      category: "ミニ丼セット",
      noodleKind: "そば",
      hotCold: "温",
      calories: 840,
      largeServingCalories: 141,
    },
    {
      id: "mini-torikara-udon",
      name: "鳥から丼セット(うどん)",
      category: "ミニ丼セット",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 792,
      largeServingCalories: 87,
    },
    {
      id: "mini-torikara-seiro",
      name: "鳥から丼セット(せいろ)",
      category: "ミニ丼セット",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 810,
      largeServingCalories: 140,
    },
    {
      id: "mini-torikara-udon-seiro",
      name: "鳥から丼セット(うどんせいろ)",
      category: "ミニ丼セット",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 783,
      largeServingCalories: 95,
    },
    {
      id: "mini-curry-soba",
      name: "カレー丼セット",
      category: "ミニ丼セット",
      noodleKind: "そば",
      hotCold: "温",
      calories: 745,
      largeServingCalories: 141,
    },
    {
      id: "mini-curry-udon",
      name: "カレー丼セット(うどん)",
      category: "ミニ丼セット",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 697,
      largeServingCalories: 87,
    },
    {
      id: "mini-curry-seiro",
      name: "カレー丼セット(せいろ)",
      category: "ミニ丼セット",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 715,
      largeServingCalories: 140,
    },
    {
      id: "mini-curry-udon-seiro",
      name: "カレー丼セット(うどんせいろ)",
      category: "ミニ丼セット",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 688,
      largeServingCalories: 95,
    },
    {
      id: "mini-oyako-soba",
      name: "親子丼セット",
      category: "ミニ丼セット",
      noodleKind: "そば",
      hotCold: "温",
      calories: 768,
      largeServingCalories: 141,
    },
    {
      id: "mini-oyako-udon",
      name: "親子丼セット(うどん)",
      category: "ミニ丼セット",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 720,
      largeServingCalories: 87,
    },
    {
      id: "mini-oyako-seiro",
      name: "親子丼セット(せいろ)",
      category: "ミニ丼セット",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 738,
      largeServingCalories: 140,
    },
    {
      id: "mini-oyako-udon-seiro",
      name: "親子丼セット(うどんせいろ)",
      category: "ミニ丼セット",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 711,
      largeServingCalories: 95,
    },
    {
      id: "mini-hirekatsu-soba",
      name: "ヒレカツ丼セット",
      category: "ミニ丼セット",
      noodleKind: "そば",
      hotCold: "温",
      calories: 858,
      largeServingCalories: 141,
    },
    {
      id: "mini-hirekatsu-udon",
      name: "ヒレカツ丼セット(うどん)",
      category: "ミニ丼セット",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 810,
      largeServingCalories: 87,
    },
    {
      id: "mini-hirekatsu-seiro",
      name: "ヒレカツ丼セット(せいろ)",
      category: "ミニ丼セット",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 828,
      largeServingCalories: 140,
    },
    {
      id: "mini-hirekatsu-udon-seiro",
      name: "ヒレカツ丼セット(うどんせいろ)",
      category: "ミニ丼セット",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 801,
      largeServingCalories: 95,
    },
  ],
  policy: {
    amountCalorieRanges: {
      かるめ: { min: 0, max: 600 },
      ふつう: { min: 600, max: 800 },
      おおめ: { min: 800, max: 1000 },
      がっつり: { min: 1000, max: null },
    },
    inari: {
      name: "いなり(二個)",
      calories: 160,
    },
    inariChance: 0.25,
    largeServingChanceByAmount: {
      おおめ: 0.45,
      がっつり: 0.7,
    },
  },
} satisfies MenuCatalog;

export const staticMenuCatalogRepository: MenuCatalogRepository = {
  loadMenuCatalog: async () => MENU_CATALOG,
};
