import type { MenuCatalog, MenuCatalogRepository } from "../domain/menu";

const MENU_CATALOG = {
  menuItems: [
    {
      id: "kake-soba-hot",
      name: "かけそば",
      category: "麺",
      noodleKind: "そば",
      hotCold: "温",
      calories: 330,
      largeServingCalories: 141,
    },
    {
      id: "tanuki-soba-hot",
      name: "たぬきそば",
      category: "麺",
      noodleKind: "そば",
      hotCold: "温",
      calories: 430,
      largeServingCalories: 141,
    },
    {
      id: "kitsune-soba-hot",
      name: "きつねそば",
      category: "麺",
      noodleKind: "そば",
      hotCold: "温",
      calories: 420,
      largeServingCalories: 141,
    },
    {
      id: "yamakake-soba-hot",
      name: "山かけそば",
      category: "麺",
      noodleKind: "そば",
      hotCold: "温",
      calories: 400,
      largeServingCalories: 141,
    },
    {
      id: "tsukimi-soba-hot",
      name: "月見そば",
      category: "麺",
      noodleKind: "そば",
      hotCold: "温",
      calories: 395,
      largeServingCalories: 141,
    },
    {
      id: "kakiage-soba-hot",
      name: "かき揚げそば",
      category: "麺",
      noodleKind: "そば",
      hotCold: "温",
      calories: 630,
      largeServingCalories: 141,
    },
    {
      id: "ika-soba-hot",
      name: "いか天そば",
      category: "麺",
      noodleKind: "そば",
      hotCold: "温",
      calories: 615,
      largeServingCalories: 141,
    },
    {
      id: "ebi-soba-hot",
      name: "えび天そば",
      category: "麺",
      noodleKind: "そば",
      hotCold: "温",
      calories: 640,
      largeServingCalories: 141,
    },
    {
      id: "torikara-soba-hot",
      name: "鳥からそば",
      category: "麺",
      noodleKind: "そば",
      hotCold: "温",
      calories: 670,
      largeServingCalories: 141,
    },
    {
      id: "mori-soba-cold",
      name: "もりそば",
      category: "麺",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 310,
      largeServingCalories: 140,
    },
    {
      id: "zaru-soba-cold",
      name: "ざるそば",
      category: "麺",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 315,
      largeServingCalories: 140,
    },
    {
      id: "hiyashi-tanuki-soba-cold",
      name: "冷したぬき",
      category: "麺",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 425,
      largeServingCalories: 140,
    },
    {
      id: "kakiage-seiro-cold",
      name: "かき揚げせいろ",
      category: "麺",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 620,
      largeServingCalories: 140,
    },
    {
      id: "ebi-seiro-cold",
      name: "えび天せいろ",
      category: "麺",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 625,
      largeServingCalories: 140,
    },
    {
      id: "ika-seiro-cold",
      name: "いか天せいろ",
      category: "麺",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 608,
      largeServingCalories: 140,
    },
    {
      id: "kake-udon-hot",
      name: "かけうどん",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 282,
      largeServingCalories: 87,
    },
    {
      id: "tanuki-udon-hot",
      name: "たぬきうどん",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 382,
      largeServingCalories: 87,
    },
    {
      id: "kitsune-udon-hot",
      name: "きつねうどん",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 372,
      largeServingCalories: 87,
    },
    {
      id: "yamakake-udon-hot",
      name: "山かけうどん",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 352,
      largeServingCalories: 87,
    },
    {
      id: "tsukimi-udon-hot",
      name: "月見うどん",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 348,
      largeServingCalories: 87,
    },
    {
      id: "kakiage-udon-hot",
      name: "かき揚げうどん",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 610,
      largeServingCalories: 87,
    },
    {
      id: "ika-udon-hot",
      name: "いか天うどん",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 600,
      largeServingCalories: 87,
    },
    {
      id: "ebi-udon-hot",
      name: "えび天うどん",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 620,
      largeServingCalories: 87,
    },
    {
      id: "torikara-udon-hot",
      name: "鳥からうどん",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 640,
      largeServingCalories: 87,
    },
    {
      id: "mori-udon-cold",
      name: "もりうどん",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 265,
      largeServingCalories: 95,
    },
    {
      id: "zaru-udon-cold",
      name: "ざるうどん",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 270,
      largeServingCalories: 95,
    },
    {
      id: "hiyashi-tanuki-udon-cold",
      name: "冷したぬき(うどん)",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 377,
      largeServingCalories: 95,
    },
    {
      id: "kakiage-udon-seiro-cold",
      name: "かき揚げせいろ(うどん)",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 605,
      largeServingCalories: 95,
    },
    {
      id: "ebi-udon-seiro-cold",
      name: "えび天せいろ(うどん)",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 612,
      largeServingCalories: 95,
    },
    {
      id: "ika-udon-seiro-cold",
      name: "いか天せいろ(うどん)",
      category: "麺",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 598,
      largeServingCalories: 95,
    },
    {
      id: "oyakodon",
      name: "親子丼",
      category: "丼単品",
      noodleKind: "なし",
      hotCold: null,
      calories: 618,
      largeServingCalories: null,
    },
    {
      id: "kakiage-don",
      name: "かき揚げ丼",
      category: "丼単品",
      noodleKind: "なし",
      hotCold: null,
      calories: 640,
      largeServingCalories: null,
    },
    {
      id: "curry-don",
      name: "カレー丼",
      category: "丼単品",
      noodleKind: "なし",
      hotCold: null,
      calories: 682,
      largeServingCalories: null,
    },
    {
      id: "tendon",
      name: "天丼",
      category: "丼単品",
      noodleKind: "なし",
      hotCold: null,
      calories: 720,
      largeServingCalories: null,
    },
    {
      id: "torikara-don",
      name: "鳥から丼",
      category: "丼単品",
      noodleKind: "なし",
      hotCold: null,
      calories: 760,
      largeServingCalories: null,
    },
    {
      id: "ebi-don",
      name: "えび天丼",
      category: "丼単品",
      noodleKind: "なし",
      hotCold: null,
      calories: 780,
      largeServingCalories: null,
    },
    {
      id: "joten-don",
      name: "上天丼",
      category: "丼単品",
      noodleKind: "なし",
      hotCold: null,
      calories: 850,
      largeServingCalories: null,
    },
    {
      id: "manpuku-joten-soba",
      name: "上天丼セット",
      category: "満腹セット",
      noodleKind: "そば",
      hotCold: "温",
      calories: 1028,
      largeServingCalories: null,
    },
    {
      id: "manpuku-kakiage-soba",
      name: "かき揚げ丼セット(大)",
      category: "満腹セット",
      noodleKind: "そば",
      hotCold: "温",
      calories: 1010,
      largeServingCalories: null,
    },
    {
      id: "manpuku-oyako-soba",
      name: "親子丼セット(大)",
      category: "満腹セット",
      noodleKind: "そば",
      hotCold: "温",
      calories: 1020,
      largeServingCalories: null,
    },
    {
      id: "manpuku-torikara-soba",
      name: "鳥から丼セット(大)",
      category: "満腹セット",
      noodleKind: "そば",
      hotCold: "温",
      calories: 1040,
      largeServingCalories: null,
    },
    {
      id: "manpuku-joten-udon",
      name: "上天丼セット(うどん)",
      category: "満腹セット",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 1010,
      largeServingCalories: null,
    },
    {
      id: "manpuku-kakiage-udon",
      name: "かき揚げ丼セット(大・うどん)",
      category: "満腹セット",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 1005,
      largeServingCalories: null,
    },
    {
      id: "manpuku-oyako-udon",
      name: "親子丼セット(大・うどん)",
      category: "満腹セット",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 1010,
      largeServingCalories: null,
    },
    {
      id: "manpuku-torikara-udon",
      name: "鳥から丼セット(大・うどん)",
      category: "満腹セット",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 1020,
      largeServingCalories: null,
    },
    {
      id: "mini-kakiage-soba",
      name: "かき揚げ丼セット",
      category: "ミニ丼セット",
      noodleKind: "そば",
      hotCold: "温",
      calories: 871,
      largeServingCalories: 141,
    },
    {
      id: "mini-oyako-soba",
      name: "親子丼セット",
      category: "ミニ丼セット",
      noodleKind: "そば",
      hotCold: "温",
      calories: 832,
      largeServingCalories: 141,
    },
    {
      id: "mini-ten-soba",
      name: "天丼セット",
      category: "ミニ丼セット",
      noodleKind: "そば",
      hotCold: "温",
      calories: 855,
      largeServingCalories: 141,
    },
    {
      id: "mini-torikara-soba",
      name: "鳥から丼セット",
      category: "ミニ丼セット",
      noodleKind: "そば",
      hotCold: "温",
      calories: 860,
      largeServingCalories: 141,
    },
    {
      id: "mini-joten-soba",
      name: "上天丼セット(ミニ)",
      category: "ミニ丼セット",
      noodleKind: "そば",
      hotCold: "温",
      calories: 888,
      largeServingCalories: 141,
    },
    {
      id: "mini-kakiage-udon",
      name: "かき揚げ丼セット(うどん)",
      category: "ミニ丼セット",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 823,
      largeServingCalories: 87,
    },
    {
      id: "mini-oyako-udon",
      name: "親子丼セット(うどん)",
      category: "ミニ丼セット",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 784,
      largeServingCalories: 87,
    },
    {
      id: "mini-ten-udon",
      name: "天丼セット(うどん)",
      category: "ミニ丼セット",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 807,
      largeServingCalories: 87,
    },
    {
      id: "mini-torikara-udon",
      name: "鳥から丼セット(うどん)",
      category: "ミニ丼セット",
      noodleKind: "うどん",
      hotCold: "温",
      calories: 812,
      largeServingCalories: 87,
    },
    {
      id: "mini-kakiage-seiro",
      name: "かき揚げ丼セット(せいろ)",
      category: "ミニ丼セット",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 853,
      largeServingCalories: 140,
    },
    {
      id: "mini-oyako-seiro",
      name: "親子丼セット(せいろ)",
      category: "ミニ丼セット",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 814,
      largeServingCalories: 140,
    },
    {
      id: "mini-ten-seiro",
      name: "天丼セット(せいろ)",
      category: "ミニ丼セット",
      noodleKind: "そば",
      hotCold: "冷",
      calories: 837,
      largeServingCalories: 140,
    },
    {
      id: "mini-kakiage-udon-seiro",
      name: "かき揚げ丼セット(うどんせいろ)",
      category: "ミニ丼セット",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 805,
      largeServingCalories: 95,
    },
    {
      id: "mini-oyako-udon-seiro",
      name: "親子丼セット(うどんせいろ)",
      category: "ミニ丼セット",
      noodleKind: "うどん",
      hotCold: "冷",
      calories: 766,
      largeServingCalories: 95,
    },
  ],
  policy: {
    amountCalorieRanges: {
      かるめ: { min: 0, max: 600 },
      ふつう: { min: 600, max: 800 },
      おおめ: { min: 800, max: 1000 },
      がっつり: { min: 1000, max: null },
    },
    inari: {
      name: "いなり(二個)",
      calories: 160,
    },
    inariChance: 0.25,
    largeServingChanceByAmount: {
      おおめ: 0.45,
      がっつり: 0.7,
    },
  },
} satisfies MenuCatalog;

export const staticMenuCatalogRepository: MenuCatalogRepository = {
  loadMenuCatalog: async () => MENU_CATALOG,
};
